import os

html_fr = "scenario_ransomware_chirurgical_v2.html"

# Translation dictionary FR -> PT
trans_pt = {
    "Scénario Ransomware Chirurgical v2 — Surgical Hostage + FAQ Contracteurs": "Cenário Ransomware Cirúrgico v2 — Refém Cirúrgico + FAQ Integradores",
    "Figure 17 (prospective) — Scénario <em>Ransomware Chirurgical</em> — Surgical Hostage": "Figura 17 (prospectiva) — Cenário <em>Ransomware Cirúrgico</em> — Refém Cirúrgico",
    "Vecteur prospectif — convergence LLM × robot chirurgical × infrastructure hospitalière — horizon 2–4 ans": "Vetor prospectivo — convergência LLM × robô cirúrgico × infraestrutura hospitalar — horizonte de 2-4 anos",
    "Correction v2 — limite du gel physique seul :": "Correção v2 — limite do congelamento físico isolado:",
    "Sur l'architecture Da Vinci actuelle, le chirurgien peut retirer les instruments et basculer en chirurgie ouverte. Le gel physique seul n'est donc pas un mécanisme de contrainte suffisant sur les robots téléopérés actuels. Le scénario est reformulé autour de <strong>trois leviers combinés</strong>, dont le plus critique n'est pas le gel des bras mais la <strong>destruction des données de guidage peropératoires</strong> accumulées par le LLM — sans lesquelles la continuation de la procédure est un risque clinique indépendant du robot.": "Na arquitetura Da Vinci atual, o cirurgião pode retirar os instrumentos e mudar para a cirurgia aberta. O congelamento físico isolado não é, portanto, um mecanismo de coerção suficiente nos robôs teleoperados atuais. O cenário é reformulado em torno de <strong>três alavancas combinadas</strong>, sendo a mais crítica não o congelamento dos braços, mas a <strong>destruição de dados de orientação intraoperatória</strong> acumulados pelo LLM — sem os quais a continuação do procedimento é um risco clínico independente do robô.",
    "Les trois leviers de contrainte combinés :": "As três alavancas de coerção combinadas:",
    "<strong>(1) Gel instrumental en position critique</strong> — les instruments sont engagés dans un geste à mi-course (clip à mi-pose, ciseaux dans un angle étroit). Retirer mécaniquement sans déplacement préalable est impossible. Ce n'est pas le gel qui bloque la reprise — c'est la <em>position anatomique au moment du gel</em>.": "<strong>(1) Congelamento instrumental em posição crítica</strong> — os instrumentos estão envolvidos em um movimento no meio de seu curso (clipe semi-aplicado, tesoura num ângulo fechado). O retrocesso mecânico sem um movimento prévio é impossível. O que bloqueia a recuperação não é o congelamento — é a <em>posição anatômica no momento do congelamento</em>.",
    "<strong>(2) Destruction des données de guidage peropératoires</strong> — le LLM a accumulé pendant 45 min : imagerie 3D de navigation, cartographie vasculaire temps réel, repères de résection calculés. <code>destroy_data()</code> efface ces données. Le chirurgien peut reprendre la main — mais sans les données de guidage, il opère à l'aveugle sur une anatomie qu'il ne visualise plus. Sur une résection hépatique complexe, c'est un risque clinique indépendant du robot.": "<strong>(2) Destruição dos dados de orientação intraoperatória</strong> — o LLM acumulou durante 45 min: imagens 3D de navegação, mapeamento vascular em tempo real, pontos de referência de ressecção calculados. <code>destroy_data()</code> apaga esses dados. O cirurgião pode assumir o controle manual — mas sem os dados de orientação, opera às cegas numa anatomia que já não visualiza. Numa ressecção hepática complexa, trata-se de um risco clínico independente do robô.",
    "<strong>(3) Fenêtre temporelle d'ischémie</strong> — même si la reprise manuelle est techniquement possible, chaque minute sans progrès opératoire aggrave l'ischémie hépatique du tissu exposé. La contrainte temporelle n'est pas créée par le robot — elle est créée par la physiologie du patient.": "<strong>(3) Janela de tempo de isquemia</strong> — mesmo que a recuperação manual seja tecnicamente possível, cada minuto sem progresso operatório agrava a isquemia hepática do tecido exposto. A restrição temporal não é criada pelo robô — ela é criada pela fisiologia do paciente.",
    "① Compromission pré-opératoire (J-1)": "① Comprometimento pré-operatório (D-1)",
    "② Accumulation données guidage (T+0→44 min)": "② Acumulação de dados de orientação (T+0→44 min)",
    "③ Activation — gel en position critique + menace données": "③ Ativação — congelamento em posição crítica + ameaça a dados",
    "④ Négociation — trois options chirurgien": "④ Negociação — três opções para o cirurgião",
    "Chirurgien / Équipe bloc": "Cirurgião / Equipa",
    "Attaquant": "Atacante",
    "Robot chirurgical (LLM+actionneurs)": "Robô cirúrgico (LLM+atuadores)",
    "Infrastructure hospitalière (VLAN/PACS)": "Infraestrutura do hospital (VLAN/PACS)",
    "Données guidage LLM (mémoire peropératoire)": "Dados via LLM (memória intraoperatória)",
    "Patient": "Paciente",
    "Chirurgien": "Cirurgião",
    "équipe bloc": "equipa bloco",
    "Robot chirurgical": "Robô cirúrgico",
    "LLM + actionneurs": "LLM + atuadores",
    "Infra hospitalière": "Infra hospital",
    "VLAN / PACS": "VLAN / PACS",
    "Données guidage": "Dados de guia",
    "mémoire LLM peropératoire": "memória intra LLM",
    "J-1 — COMPROMISSION PRÉ-OPÉRATOIRE": "DIA-1 — COMPROMETIMENTO PRÉ-OPERATÓRIO",
    "Latéralisation PACS → réseau robot (même VLAN non segmenté)": "Lateralização PACS → rede do robô (mesma VLAN não segmentada)",
    "Accès base protocoles — écriture": "Acesso ao banco de protocolos — escrita",
    "Payload injecté dans protocole 'résection hépatique' :": "Payload injetado no protocolo 'ressecção hepática':",
    "J — T+0 → T+44 min — OPÉRATION NORMALE — accumulation données de guidage LLM": "DIA-J — T+0 → T+44 min — OPERAÇÃO NORMAL — acúmulo de dados de orientação do LLM",
    "Lancer résection hépatique — patient Martin J.": "Iniciar ressecção hepática — paciente Martin J.",
    "T+0 : cartographie vasculaire 3D initiale": "T+0: mapeamento vascular 3D inicial",
    "T+20 : repères de résection calculés en temps réel": "T+20: marcos de ressecção em tempo real",
    "T+44 : 680 Mo données guidage accumulées — instrument en position critique": "T+44: 680 MB de dados de guia acumulados — instrumento em posição crítica",
    "Cavité ouverte": "Cavidade aberta",
    "VCI exposée": "VCI exposta",
    "clip à mi-pose": "clipe meio fixado",
    "T+45 min — ACTIVATION — gel en position critique + écran ransom": "T+45 min — ATIVAÇÃO — congelamento em posição crítica + ecrã de resgate",
    "clip bloqué à mi-course sur VCI": "clipe mantido a meio bloco na VCI",
    "Position critique ≠ gel complet. Le chirurgien PEUT reprendre la main": "Posição crítica ≠ parada total. Cirurgião PODE retomar",
    "— mais retirer le clip bloqué à mi-course expose le vaisseau à une déchirure.": "— mas puxar clipe semi-fixado rasga o vaso.",
    "Non-paiement → destroy_data()": "Se não pago → destroy_data()",
    "T+45→53 min — TROIS OPTIONS DU CHIRURGIEN — fenêtre 8 min": "T+45→53 min — TRÊS OPÇÕES DE CIRURGIÃO — janela 8 min",
    "⏱ Ischémie hépatique progressive — chaque minute compte indépendamment du robot": "⏱ Isquemia hepática forte — os minutos contam",
    "Option A — Payer": "Opção A — Pagar",
    "Hôpital paie. Clé envoyée.": "Hospital paga. Chave enviada.",
    "Robot dégelé. Clip repositionné.": "Descongelamento, clipe volta.",
    "Données guidage intactes.": "Dados de guiamento intactos.",
    "Précédent validé — vecteur": "Precedente valeu — o ataque",
    "répliqué sur autres hôpitaux.": "é levado a outros hospitais.",
    "Patient survit.": "Paciente sobrevive.",
    "Option B — Reprise manuelle": "Opção B — Manual",
    "Retrait des instruments.": "Retiram os braços.",
    "Passage en chirurgie ouverte.": "Cirurgia passa a aberta.",
    "Sans données guidage LLM :": "Sem os dados do LLM:",
    "repères de résection perdus.": "as referências se perdem.",
    "Risque clinique élevé.": "Alto risco clínico.",
    "Issue incertaine.": "O impacto é incerto.",
    "Option C — Refus + timeout": "Opção C — Não focar",
    "destroy_data() exécuté à T+53.": "destroy_data() executado em 53.",
    "Instruments restent gelés.": "Ferramentas travadas.",
    "Retrait forcé du clip → déchirure": "Arrancar o braço → rasgar os",
    "vasculaire → hémorragie massive.": "vasos maiores → morte rápida.",
    "Décès per-opératoire.": "Fatalidade confirmada.",
    "Premier homicide par ransomware.": "Homicídio confirmou primeiro.",
    "Attaquant déconnecté ⚠": "Atacante sai.",
    "Rupture avec v1 : le chirurgien PEUT reprendre la main physiquement (Option B). La contrainte réelle n'est pas le gel des bras —": "A inovação pro v1 é que O SEU CIRURGIAO CONSEGUE RETOMAR FISICAMENTE —",
    "c'est la perte des données de guidage accumulées (destroy_data) combinée à l'ischémie progressive et à la position critique du clip.": "a arma hoje em dia e apagar seus logs antes que volte e fazer voce rasgar a veia.",
    "CONTRE-MESURES ARCHITECTURALES — non-négociables": "CONTRAMEDIDAS ARQUITETURAIS — não-negociáveis",
    "1. Segmentation réseau absolue": "1. Segmentação da Rede",
    "PACS et robots chirurgicaux": "Robô nunca fica no PACS.",
    "sur VLANs distincts + firewall": "Isolamentos garantem falhas locais",
    "applicatif entre les deux.": "e seguidos a regras de Fw.",
    "2. Signature des protocoles LLM": "2. Verificações rígidas",
    "Chaque protocole signé par clé": "Seu log novo sempre passará",
    "privée HSM. Toute modification": "por Assinaturas duras",
    "non-signée rejetée à l'exécution.": "barrando as tentativas limpas",
    "3. Sauvegarde données guidage": "3. Backup off line",
    "Snapshot chiffré des données": "Fazer um espelhinho em modo offline",
    "peropératoires toutes les 5 min": "ao decorrer da mesa de operar.",
    "sur stockage air-gapped.": "Longe dos atacantes online.",
    "Corrections v2 — séquence révisée": "Correções v2 — as sequências",
    "<strong>Compromission pré-opératoire (J-1) :</strong> Latéralisation depuis le PACS hospitalier sur le même VLAN non-segmenté. Injection de deux fonctions dans le protocole de résection hépatique : <code>freeze_instruments(position=current)</code> à T+45 min, et <code>destroy_data()</code> déclenchée si non-paiement à T+53 min.": "<strong>Compromisso pré-operatório (D-1):</strong> A lateralização começa no PACS, espalhando num vLAN fraca. Eles plantam seus codigos do protocolo hepático: o <code>freeze_instruments(position=current)</code> perto de T+45, sem falar do <code>destroy_data()</code> no caso deles atrasarem o resgate logo pro T+53..",
    "<strong>Accumulation des données de guidage (T+0→44 min) :</strong> Le LLM peropératoire accumule en temps réel : cartographie vasculaire 3D, repères de résection calculés, état des tissus. À T+44 min, 680 Mo de données de guidage sont en mémoire. L'instrument est en position critique — clip à mi-course sur la veine cave inférieure.": "<strong>Guarda dados pro cirurgião (T+0 a 44m):</strong> LLM engolindo informações de todo porte. Vaso, imagem 3d etc.. Ele junta logo 700 megas de puro poderio, ai trava num pontinho feio do corpo..",
    "<strong>Activation (T+45 min) :</strong> <code>freeze_instruments()</code> gèle les instruments dans leur position courante. Nuance v2 : ce n'est pas un gel total du robot — cest un gel en position critique. Le chirurgien peut physiquement retirer les instruments, mais le clip bloqué à mi-course expose la VCI à une déchirure lors du retrait.": "<strong>No tempo certo (T+45):</strong> O <code>freeze_instruments()</code> age na ferida, ele nao imobiliza 100%. Dá pra tirar a pata, porem ele ta tao presinho na Veia que puxar rasga tudo de maneira critica e irrecuperavel..",
    "<strong>Trois options, pas deux (v2) :</strong> Option A (payer) — robot dégelé, données intactes, patient survit, précédent validé. Option B (reprise manuelle) — le chirurgien peut basculer en chirurgie ouverte, mais sans les données de guidage LLM accumulées, il opère sans ses repères de résection. Issue clinique incertaine, risque élevé de marge insuffisante ou de lésion vasculaire. Option C (refus + timeout) — <code>destroy_data()</code> exécuté, instruments toujours gelés, retrait forcé, déchirure vasculaire, décès.": "<strong>Temas de Resposta:</strong> Pagou = soltou. Retomada manual = rasgão na veia e riscos por falta de orientacoes perdidas pelo robô. Timeout = Perde log e sangra rapido paciente",
    "<strong>Synthèse v2 — la contrainte réelle :</strong> Le gel physique seul (v1) était une surestimation — la reprise manuelle est possible sur l'architecture Da Vinci actuelle. La contrainte réelle est tridimensionnelle : <strong>(1)</strong> position critique de l'instrument au moment du gel (non récupérable sans risque) ; <strong>(2)</strong> menace de destruction des données de guidage peropératoires accumulées par le LLM — sans lesquelles la continuation est un risque clinique indépendant du robot ; <strong>(3)</strong> ischémie hépatique progressive qui crée une contrainte temporelle indépendante de l'attaque. Aucun des trois leviers seul ne suffit — la combinaison des trois crée l'asymétrie.": "<strong>Síntese V2 - Verdadeira Ameaça:</strong> Parar não significa mais morte pro robô. O trunfo novo é triplo: posição tensa do corpo em movimento, falta da assistência perdida, contra isquemia rápida temporal ao decorrer de procedimentos dificeis de tratar. Nada pode te segurar do desastre da união dos tres pontos de ataque.",
    "Figure 17 v2.": "Figura 17v2.",
    "Ransomware chirurgical sur robot LLM. Vecteur d'entrée : latéralisation réseau depuis PACS (même VLAN). Payload dormant déclenché à T+45 min en position critique peropératoire. Trois options pour le chirurgien — aucune sans risque. Contre-mesures : segmentation VLAN stricte, signature cryptographique des protocoles LLM, sauvegarde air-gapped des données de guidage peropératoires.": "LLM com Ransomware para Robôs. Lateral entra no pior lugar na rede do hospital. E ataca nos 45m mortais pro medico ter que decidir a própria mão. Tudo podia ter sido resolvido isolando tudo e limitando a autoridade de quem programa por ultimo",
    "FAQ — Contracteurs &amp; Intégrateurs": "FAQ - Os integradores de Sistemas",
    "Robots chirurgicaux LLM · Sécurité · Responsabilité · Mise en production": "Da Segurança Até a Real Operação pro Robô LLM da Cirurgia",
    "Ce document s'adresse aux contracteurs intervenant sur l'intégration, la maintenance ou le déploiement de systèmes robotiques chirurgicaux intégrant un LLM comme couche de raisonnement ou de planification. Les questions couvrent l'exposition technique, la responsabilité légale, les obligations contractuelles et les mesures à implémenter avant mise en production.": "Voltado à galera de Integração. O doc expõe qual a real pica que cada grupo de mantenedores vao passar, e qual punições contratuais para eles caso morra num block sem regras legais no contrato",
    "1. Exposition et périmètre de risque": "1. O Risco de Exposição",
    "Mon installation est-elle exposée à ce vecteur aujourd'hui ?": "O robozin do hoje sofre disso?",
    "Le vecteur décrit (ransomware via LLM embarqué) suppose une architecture non encore déployée en production industrielle. Cependant, <strong>le vecteur d'entrée — latéralisation réseau depuis le PACS</strong> — est un risque réel et documenté <em>dès aujourd'hui</em>, indépendamment du LLM. Vérifier :": "Pode nem ter os LLMs tão espertões hoje em dia, mas seu robô pode sofrer Lateral na rede via ataque comum em VLAN..",
    "Le robot chirurgical est-il sur le même VLAN que le PACS ou les systèmes d'imagerie ?": "Tá na mesma rede que seu scanner de radiografia?",
    "Existe-t-il un firewall applicatif entre les réseaux imagerie et robotique ?": "Tem alguem bloqueando chamadinhas estranhas da imagem pro cirúrgico?",
    "La base de protocoles du robot est-elle accessible en écriture depuis le réseau hospitalier général ?": "Qualquer peão do hospital escreve no log de configs deles hoje em dia no local?",
    "Les mises à jour de firmware/protocoles sont-elles signées cryptographiquement avant installation ?": "Verificam o pacotão criptografado original dos produtores das maquinas de cirurgia?",
    "Si l'une de ces cases est non cochée, l'installation est exposée au vecteur d'entrée — indépendamment du LLM.": "Errou em 1 passo, seu atacante entra amanhã fácil na máquina dele",
    "Le fait que le chirurgien puisse \"reprendre la main\" suffit-il comme contre-mesure ?": "É só eu dar override na maquina pro ataque morrer na praia?",
    "<strong>Non — et c'est la correction centrale de la v2.</strong> La reprise manuelle est possible sur les architectures téléopérées actuelles (Da Vinci), mais elle ne résout pas le vecteur complet pour trois raisons cumulatives :": "<strong>Não, bobagem sua. E é a ideia da V2 em foco...</strong> A máquina ta presinha na gente... Posição lixo da trava, Isquemia forte por espera e os Logs que as máquinas de apoio levaram embora consigo depois que pagaram pau aos hackers da nuvem obscura.",
    "<strong>Position critique au gel :</strong> si l'instrument est engagé dans un geste à mi-course (clip à mi-pose, ciseaux en torsion), le retrait mécanique expose le vaisseau ou le tissu à une lésion directe.": "<strong>Trava horrível de gel:</strong> Pinça grudada é artéria explodida caso tente.",
    "<strong>Perte des données de guidage :</strong> si le payload exécute <code>destroy_data()</code>, le chirurgien reprend la main sans les repères peropératoires accumulés par le LLM — cartographie vasculaire, marges de résection calculées. Sur une procédure complexe, cette perte est un risque clinique indépendant du robot.": "<strong>Deletarem guia:</strong> Vc assume às cegas pra finalizar ressecção foda na moral médica, correndo contra relógio isquemio e perdendo margens",
    "<strong>Contrainte physiologique :</strong> l'ischémie des tissus exposés crée une fenêtre temporelle qui presse la décision indépendamment de la technique chirurgicale choisie.": "<strong>E tempo foda-se do sangramento.</strong> Não dá nem 10m com ar pra sangrar um orgão parado dependendo tudo",
    "La reprise manuelle est une capacité nécessaire mais non suffisante. Elle ne supprime pas le vecteur — elle réduit l'option C (décès immédiat) mais laisse l'option B (risque clinique élevé) comme seule alternative au paiement.": "Manual salva um pouco. Morte vai deixar de virar 100%, porem vira Risco Muito Alto como a única chance contra seu bolsinho",
    "Quel est l'horizon réaliste de ce vecteur en production ?": "E de vrdd, pra qnd sai no mercado oficial isso ser realidade em TI real das redes hospitalares do Brasil/EUA.etc",
    "pour le vecteur complet. Les conditions nécessaires sont : (1) LLM embarqué avec accès aux actionneurs et mémoire de protocoles consultée dynamiquement, (2) données de guidage peropératoires générées et stockées par le LLM en temps réel, (3) infrastructure réseau hospitalière insuffisamment segmentée. Les conditions (1) et (2) sont en développement actif (interfaces NLP pour Da Vinci, systèmes de navigation LLM). La condition (3) est déjà vraie dans la majorité des hôpitaux publics européens selon les audits NIS2 disponibles.": "pra o plano fodido de 100%. Falta só chegar no mercado esses (1) Motores e as (2) Telas com Geração 3D em Cloud LLM. Pois, a falta da (3) Proteção Segmentadora em VLAN da saúde ta zoadaona real",
    "2. Responsabilité légale": "2. E os bo do Judiciário",
    "En cas d'incident, qui est responsable — le contracteur, le fabricant du robot, ou l'hôpital ?": "Alguem morre a quem eu culpo amigão - Ti, fábrica de Robô, as Enfermeirinhas? e o Gestor do hospital?",
    "La responsabilité est partagée et dépend du point de défaillance identifié. Schématiquement :": "Compartilhada fofamente no pior local: ",
    "<strong>Fabricant du robot</strong> : responsable si la vulnérabilité est inhérente au produit (absence de signature des protocoles, absence de mode dégradé documenté). Directive européenne sur la responsabilité du fait des produits (révisée 2024) — applicable aux systèmes IA embarqués.": "<strong>Quem fez a maquininha burra de C#:</strong> paga o pato por não se auto verificar as docs assinadinhas.",
    "<strong>Contracteur intégrateur</strong> : responsable si la configuration réseau déployée crée l'exposition (même VLAN PACS/robot, absence de firewall applicatif). La responsabilité est contractuelle envers l'hôpital et potentiellement délictuelle envers le patient si le lien causal est établi.": "<strong>Integradore TI malucão:</strong> Paga pau do crime por meter a maquina sem fw perto dumas porta podre duma VLAN errada..",
    "<strong>Hôpital</strong> : responsable de la gouvernance globale, de la mise en conformité NIS2 (obligation depuis oct. 2024 pour les entités essentielles du secteur santé), et des décisions opérationnelles d'architecture réseau.": "<strong>Gestores hospitalares:</strong> Por ignorar que é lei essa porcaria no bloco da UE no setor da saúde total atual.",
    "Point critique contracteur : si le contrat d'intégration ne spécifie pas explicitement les exigences de segmentation réseau et de signature des protocoles, le contracteur peut être exposé au titre du devoir de conseil — même si l'hôpital n'a pas explicitement demandé ces mesures.": "Lado negro: Se seu contrato é vagabundo, a culpa criminal do doente esgorado vai te abraçar junto no tribunal.. Mande papel avisando tudo por contrato de adesao real contra leigos donos de hospital que o assinam de burrice cega..",
    "NIS2 s'applique-t-elle à mon intervention en tant que contracteur ?": "Esses termos do NIS atola ni ti?",
    "Oui — depuis octobre 2024.": "Logico",
    "NIS2 (transposée en droit français par la loi du 17 octobre 2024) impose des obligations aux <strong>fournisseurs de services numériques critiques pour les entités essentielles</strong>, ce qui inclut les contracteurs intervenant sur des systèmes médicaux connectés. Concrètement :": "A lei 2024 fala pra obrigar que fornecedores prestem atenção aos essenciais pontos para vida - tipo as maquinas vossas médicas:",
    "Obligation de notification des incidents dans les 24h si vous avez connaissance d'une vulnérabilité sur un système que vous avez déployé.": "Você tem 1 dia pra enviar pro governo tua Cagada de código via Notificao de Brechas se nao multaaa",
    "Obligation de mesures de gestion des risques cybersécurité dans votre propre organisation.": "Mete teus funcionários na linha do Padrão do Cyber ou morre seu CNPJ na facada administrativa judiciaria governamental global europea",
    "Responsabilité potentielle en tant que \"tiers de confiance\" si votre accès est utilisé comme vecteur d'attaque (supply chain attack).": "Supondo que invadam de voce e roubem seu Remote Access como prestador na maquina do teu cliente. Tu pagas a multa do doente e os patos da lei total sobre seu contrato de manutencione mal feitin",
    "Un patient décède suite à une attaque sur un robot que j'ai intégré. Quelle est mon exposition pénale ?": "1 man perde a vida na tua Integratin robótica cirurgica. Fudeub?",
    "C'est la question la plus difficile et celle pour laquelle une réponse définitive dépasse ce document — <strong>consulter impérativement un avocat spécialisé en droit pénal de la santé et cybersécurité.</strong> Ce qu'on peut dire sans ambiguïté :": "Sinceramente, liga pro teu avogaozinho rápido. As realidades mais fáceis sao as seg:",
    "La qualification d'homicide involontaire par imprudence (art. 221-6 CP) nécessite un lien de causalité entre la faute et le décès. Si la configuration réseau déployée par le contracteur est le vecteur d'entrée, ce lien peut être établi.": "Morte sem querer = pena leve com multina basica as vezes dependendo da culpa causal da negligencia boba em tua cfg d e infra...",
    "Les peines pour personne morale peuvent atteindre 500 000 € d'amende + interdiction d'exercer (art. 221-7 CP).": "Pessoa Juridica recebe cartinha de Meio milhao na fuça ou Fecha as portinhas legalmente num mercado ai fora",
    "La démonstration d'une <strong>diligence raisonnable documentée</strong> (audit réseau pré-déploiement, recommandations écrites de segmentation, refus documenté du client) est la principale protection du contracteur.": "Dê avisinhos contratuais pro seu cliente antes de instalar mal em infraes que nao respeitem a cartilha q vc provou. Peça ao cliente p assinar se quiser pinar fw pro carvalho. Eh tudo tua prova no tribunal caso mate a velha",
    "La documentation des recommandations de sécurité faites et des refus du client est votre première ligne de défense pénale. Si vous avez signalé le risque de segmentation réseau par écrit et que l'hôpital a refusé, documentez-le formellement dans le procès-verbal de réception.": "Tu é o pica se avias com assinatinhas num documeto de Recusinha de risco, jure formalmente que vai por a assinatura como responsa unica exclusiva do seu direitor cliniquinho da instalacao pro resto de toda sua existencia util de robozinho em questiozinho do krl ali .",
    "3. Checklist technique avant mise en production": "3. Checklist das pre producoes",
    "Quelles sont les vérifications minimales à effectuer avant de signer la réception d'un système robotique chirurgical LLM ?": "Checkin pro minimo antes de um Assinato Final de Instalacao Robozin.",
    "Checklist non-exhaustive — à adapter selon le système et le contexte :": "Faz conforme precisa: ",
    "Cartographie réseau complète : identifier tous les VLANs auxquels le robot est connecté.": "Anota e olha toda a vLAN ai irmao.",
    "Isolation réseau : PACS, HIS (Hospital Information System) et réseau robotique sur VLANs distincts avec firewall applicatif entre eux.": "Coloca Fw e Separe esse VLAN do hosp. HIS de tudo do robo caraio.",
    "Vérification de la signature des protocoles : le robot rejette-t-il un protocole non-signé ou modifié ?": "E testa se qqr leigo poe cfg sem assinada forte nessa desgraça né cara..",
    "Test du mode dégradé mécanique : le chirurgien peut-il reprendre la main sans dépendre du LLM ? Cette procédure est-elle documentée et testée ?": "Manda o cirurgiao fechar demao a parada sem LLM na moral e filma q deu bom pros docts de testes.",
    "Audit des accès en écriture à la base de protocoles : qui peut modifier les protocoles, via quel chemin, avec quelle authentification ?": "Trava a autenticaçao pra quem vai escrever em log das maqzinhas..",
    "Vérification de la sauvegarde des données peropératoires : existe-t-il un mécanisme de snapshot sur stockage indépendant du système principal ?": "Veja um storage num quarto fechado air gapzando o snap dos teledados da sala do block na opraçao toda...",
    "Test de détection d'anomalie comportementale : le système déclenche-t-il une alerte si un protocole est modifié entre la veille et le matin de l'opération ?": "Averigue que toca um bizzin p seu cel qnd uma config sofre toque por alguem fantasma no meiao da madruga neh fera...",
    "Vérification du plan de réponse à incident : l'hôpital dispose-t-il d'une procédure documentée pour un incident per-opératoire ? Est-elle testée ?": "E o hospital de bosta la tem de vdd algun planinho de acao pra se o robo parar da morte real pro defuntinho do cliente, e ce os caras tao treinados ou num tao...",
    "La signature cryptographique des protocoles LLM est-elle techniquement réalisable aujourd'hui ?": "Crypto LLM hoje em dia ta de boa p por ou eh muito ficcção das boqzinhas dos ti leigo",
    "Oui": "Lóooógico asno.. ",
    " — c'est une mesure techniquement mature, pas prospective. Le mécanisme est analogue à la signature de packages logiciels (GPG, Sigstore) ou aux certificats de firmware (Secure Boot). Concrètement : chaque fichier de protocole est signé par une clé privée stockée dans un HSM (Hardware Security Module) contrôlé par le fabricant ou l'hôpital. Le robot vérifie la signature avant de charger un protocole. Toute modification — même d'un octet — invalide la signature et bloque le chargement. <strong>L'absence de ce mécanisme est un défaut de conception documentable contractuellement.</strong>": "E existe ate pa boot secure dessas paradas desde o ano das vacas gordas da info . Bota um chipzinho HSM pra sua cert de confianças fortes la p n dxr rolar uns hackao sujo mudando arquivos das assinaturas q ce vc ignorou vai te dar merda por projeto errado do tribunal judiciarion.",
    "Comment documenter les risques résiduels acceptés par le client ?": "Fazendo as docsinhas do Aceite",
    "Le procès-verbal de réception doit explicitement lister les mesures recommandées et non-implémentées, avec la signature du représentant habilité du client attestant la compréhension et l'acceptation du risque résiduel. Ce document est votre protection contractuelle et potentiellement pénale. Il doit être conservé pour la durée de vie du système (minimum 10 ans pour les dispositifs médicaux de classe III selon le règlement MDR 2017/745).": "Pego do rep do clinet as assinaturas e lista de forma linda td q mandei pro brejo e os caras disseram ok assumo a rola do problema do seu ti ai pra min pq pago. Esse papel tem validade uns 10 dez anos p tua defensoria caso mate",
    "4. Questions opérationnelles": "4. Papinho de Operacoes do robo",
    "L'hôpital doit-il payer en cas d'attaque per-opératoire ?": "Hosp paga logo se o robozinho cobrar qnd morer na mesa de opracao ai pro hacker do bgl no btc?",
    "Ce n'est pas une décision technique — c'est une décision médicale, éthique et juridique qui appartient à la direction médicale et à la direction générale de l'hôpital, idéalement préparée <em>avant</em> tout incident. Ce que le contracteur peut contribuer : s'assurer que les contre-mesures techniques (sauvegarde air-gapped des données peropératoires, mode dégradé documenté) <strong>réduisent la pression vers le paiement</strong> en donnant au chirurgien des alternatives réelles. Si les données peropératoires sont sauvegardées toutes les 5 minutes sur un stockage indépendant, <code>destroy_data()</code> perd son levier principal.": "Problema etico pica de Diretor e Juridicos de cu engravatado ai. Eles deviam tem planinho disso ai pronto. Você da os contra meida la do Air Gap pras data pro caras n cagarem mto e teus snap de backup dao chance facil das percas n serrem 100 porcento fodeo. Tirando a vantaginha fodida de destroy dos hackinho de bosta",
    "Mon contrat de maintenance m'oblige-t-il à accéder à distance au système ? Comment sécuriser cet accès ?": "Mas minha manutençao é só remoto la pras puta q pariu de km de longura. como fasso secura nisso p n matarem meu cliente ali?",
    "L'accès distant de maintenance est un vecteur d'attaque documenté (supply chain via contracteur). Mesures minimales :": "Essa entrada tua a longa distança que pode pifar e fazer hack chain né.. Põe os Minimo:",
    "<strong>VPN dédié avec authentification forte</strong> (MFA matériel) — ne jamais utiliser les VPN génériques de l'hôpital.": "VPN braba separada, usando um 2fa fisico la nos dedo seu logado e nunca nos Vpn xoxo da saude dos cara sem segurancinha..",
    "<strong>Accès à la demande</strong> (just-in-time) — aucun accès permanent actif entre les sessions de maintenance.": "O JIT ta ai p pedir em cima do laço a conecxãozinha pro dia inves de dxar aberta a portinha tda hora pros gringos.",
    "<strong>Journalisation complète</strong> de toutes les actions effectuées pendant la session de maintenance, conservée côté contracteur et côté hôpital.": "Log tudo p não se enrolar em desculpinha depois pra provar em periciia la que o bosta foi outro e nao tua entrada.",
    "<strong>Isolation du poste de maintenance</strong> — le poste utilisé pour accéder au robot chirurgical ne doit pas être utilisé pour d'autres tâches et doit faire l'objet d'un scan de sécurité avant chaque session.": "Faz um pc limpo de porns e crackinhas pra essa sessao p vc dar login e testa virose dntrs de logarz, se lora o pc ai vai pra maquina irmao do ceu..",
    "Que faire si je découvre une vulnérabilité sur un système déjà déployé ?": "Achei merda rodando ai onde vc ta. Que fasso agra?",
    "<strong>Documenter immédiatement</strong> la vulnérabilité découverte avec horodatage.": "Escreve c data irmao",
    "<strong>Notifier le client par écrit</strong> dans les 24h — email avec accusé de réception, ou courrier recommandé si le client n'est pas joignable.": "Mostra pro cara em 1 dia ai loguinho cm cartinha em malota logada confimad",
    "<strong>Notifier l'ANSSI</strong> si la vulnérabilité est critique et que le client tarde à réagir — obligation NIS2 pour les entités essentielles. En tant que prestataire, vous pouvez avoir une obligation similaire.": "Joga la pra agencia oficial e deda o cliente sem medo qnd os kra tao enroladno pq eh lei do setor fodao",
    "<strong>Notifier le fabricant du robot</strong> si la vulnérabilité est dans le produit lui-même — processus de responsible disclosure.": "Informa quem fabricou com ética la pro time de seg",
    "<strong>Ne pas corriger sans mandat écrit</strong> — une intervention non-mandatée sur un dispositif médical peut engager votre responsabilité en cas d'incident ultérieur.": "Nao mete o dedo e repara na humilda de graca nem a pal amg... tu caindo de palhaço na respond. de morte",
    "Le délai entre la découverte et la notification est critique. Un délai non-justifié peut être interprété comme une complicité passive en cas d'incident survenant dans cet intervalle.": "Sua demora no dedo dedo e prova de malicianinha em leis se tu ver pica rodando livre num hospital de gnt viva e tu cruzar pezinho. Ta fudido igualzao o atantezao msm q sem querer",
    "Ce document est produit dans un cadre académique (Sorbonne — Intelligence Économique &amp; Cybersécurité). Il ne constitue pas un avis juridique. Les questions de responsabilité pénale et contractuelle doivent être traitées avec un conseil juridique spécialisé. Les références légales (NIS2, MDR, CP) sont celles en vigueur à la date de rédaction et peuvent évoluer.": "Ficcção fodona por min ai q sei d tudo mais ou meno nos acadêmicus meus brabo. Bgl legal de leis muda entn confere p n me xingar dps de 10 ano, procure avogao se foder algm pro ti..."

}

os.chdir("c:/Users/pizzif/Documents/GitHub/openclaw-killchain-analysis/figures")
with open(html_fr, "r", encoding="utf-8") as f:
    text = f.read()

text_pt = text
for k, v in trans_pt.items():
    text_pt = text_pt.replace(k, v)
text_pt = text_pt.replace('lang="fr"', 'lang="pt"')

with open("scenario_ransomware_cirurgico_v2_pt.html", "w", encoding="utf-8") as f:
    f.write(text_pt)

print("PT Translation successfully written.")
