#!/usr/bin/env python3
"""
OpenClaw — Figure 20 : Defense
========================================
Generates Figure20_Defense_FR.png and Figure20_Defense_EN.png

EDIT: Change text directly in SVG_FR / SVG_EN below.

Usage:
    python3 fig20_defense.py              # FR + EN
    python3 fig20_defense.py fr           # FR only
    python3 fig20_defense.py en           # EN only

Requires: pip install cairosvg
"""

import os, sys

try:
    import cairosvg
except ImportError:
    print("pip install cairosvg")
    sys.exit(1)

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "openclaw_figures")
DPI = 300
WIDTH = 3600

# ────────────────────────────────────────────────────────────
# SVG FRANÇAIS (modifiable)
# ────────────────────────────────────────────────────────────
SVG_FR = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<svg xmlns="http://www.w3.org/2000/svg" width="780" height="480" viewBox="0 0 780 480">\n'
    '  <style>\n'
    '    text { font-family: "Times New Roman", Times, serif; }\n'
    '    .title { font-size: 11px; font-weight: bold; text-anchor: middle; }\n'
    '    .layer { stroke: #000; stroke-width: 1; }\n'
    '    .stage-label { font-size: 8px; font-weight: bold; text-anchor: middle; }\n'
    '    .control-text { font-size: 7.5px; text-anchor: middle; fill: #333; }\n'
    '    .maturity { font-size: 7px; text-anchor: middle; fill: #555; font-style: italic; }\n'
    '    .caption { font-size: 10px; text-anchor: start; }\n'
    '    .arrow { fill: none; stroke: #000; stroke-width: 0.6; marker-end: url(#arr); }\n'
    '    .block { font-size: 7px; text-anchor: middle; fill: #c00; font-weight: bold; }\n'
    '  </style>\n'
    '  <defs><marker id="arr" markerWidth="6" markerHeight="4" refX="6" refY="2" orient="auto"><polygon points="0 0, 6 2, 0 4" fill="#000"/></marker></defs>\n'
    '\n'
    '  <text x="390" y="20" class="title">DÉFENSE EN PROFONDEUR — POINTS D\'INTERRUPTION DE LA KILL CHAIN</text>\n'
    '  <line x1="20" y1="28" x2="760" y2="28" stroke="#000" stroke-width="0.6"/>\n'
    '\n'
    '  <!-- Attack flow arrow at top -->\n'
    '  <line x1="40" y1="42" x2="740" y2="42" class="arrow"/>\n'
    '  <text x="390" y="38" class="maturity">Progression de l\'attaque →</text>\n'
    '\n'
    '  <!-- 7 columns, each ~100px -->\n'
    '  <!-- Stage 1 -->\n'
    '  <rect x="25" y="50" width="100" height="40" fill="#f5f5f5" class="layer"/>\n'
    '  <text x="75" y="67" class="stage-label">1. Recon.</text>\n'
    '  <text x="75" y="78" class="maturity">J−30 à J−15</text>\n'
    '\n'
    '  <rect x="25" y="100" width="100" height="65" fill="#eee" class="layer"/>\n'
    '  <text x="75" y="115" class="control-text">Réduction empreinte</text>\n'
    '  <text x="75" y="127" class="control-text">publique, hardening</text>\n'
    '  <text x="75" y="139" class="control-text">bannières, sensibil.</text>\n'
    '  <text x="75" y="155" class="maturity">Basique</text>\n'
    '\n'
    '  <!-- Stage 2 -->\n'
    '  <rect x="130" y="50" width="100" height="40" fill="#f5f5f5" class="layer"/>\n'
    '  <text x="180" y="67" class="stage-label">2. Armement</text>\n'
    '  <text x="180" y="78" class="maturity">J−15 à J−7</text>\n'
    '\n'
    '  <rect x="130" y="100" width="100" height="65" fill="#eee" class="layer"/>\n'
    '  <text x="180" y="115" class="control-text">Revue de code skills,</text>\n'
    '  <text x="180" y="127" class="control-text">signature éditeurs,</text>\n'
    '  <text x="180" y="139" class="control-text">allowlist extensions</text>\n'
    '  <text x="180" y="155" class="maturity">Intermédiaire</text>\n'
    '\n'
    '  <!-- Stage 3 -->\n'
    '  <rect x="235" y="50" width="100" height="40" fill="#f0f0f0" class="layer"/>\n'
    '  <text x="285" y="67" class="stage-label">3. Livraison</text>\n'
    '  <text x="285" y="78" class="maturity">J−7 à J</text>\n'
    '\n'
    '  <rect x="235" y="100" width="100" height="65" fill="#e8e8e8" class="layer"/>\n'
    '  <text x="285" y="115" class="control-text">Patch KEV/CISA,</text>\n'
    '  <text x="285" y="127" class="control-text">MFA résistante,</text>\n'
    '  <text x="285" y="139" class="control-text">sandboxing skills</text>\n'
    '  <text x="285" y="155" class="maturity">Basique</text>\n'
    '\n'
    '  <!-- Stage 4 -->\n'
    '  <rect x="340" y="50" width="100" height="40" fill="#e8e8e8" class="layer"/>\n'
    '  <text x="390" y="67" class="stage-label">4. Exploitation</text>\n'
    '  <text x="390" y="78" class="maturity">Jour J</text>\n'
    '\n'
    '  <rect x="340" y="100" width="100" height="65" fill="#e0e0e0" class="layer"/>\n'
    '  <text x="390" y="115" class="control-text">Allowlist outils,</text>\n'
    '  <text x="390" y="127" class="control-text">restrictions</text>\n'
    '  <text x="390" y="139" class="control-text">permissions agent</text>\n'
    '  <text x="390" y="155" class="maturity">Intermédiaire</text>\n'
    '\n'
    '  <!-- Stage 5 -->\n'
    '  <rect x="445" y="50" width="100" height="40" fill="#e0e0e0" class="layer"/>\n'
    '  <text x="495" y="67" class="stage-label">5. Installation</text>\n'
    '  <text x="495" y="78" class="maturity">J à J+1</text>\n'
    '\n'
    '  <rect x="445" y="100" width="100" height="65" fill="#d8d8d8" class="layer"/>\n'
    '  <text x="495" y="115" class="control-text">Gouvernance</text>\n'
    '  <text x="495" y="127" class="control-text">mémoire, rotation</text>\n'
    '  <text x="495" y="139" class="control-text">tokens, intégrité</text>\n'
    '  <text x="495" y="155" class="maturity">Intermédiaire</text>\n'
    '\n'
    '  <!-- Stage 6 -->\n'
    '  <rect x="550" y="50" width="100" height="40" fill="#d8d8d8" class="layer"/>\n'
    '  <text x="600" y="67" class="stage-label">6. C2</text>\n'
    '  <text x="600" y="78" class="maturity">J+1 à J+5</text>\n'
    '\n'
    '  <rect x="550" y="100" width="100" height="65" fill="#d0d0d0" class="layer"/>\n'
    '  <text x="600" y="115" class="control-text">Allowlist egress,</text>\n'
    '  <text x="600" y="127" class="control-text">DLP, inspection</text>\n'
    '  <text x="600" y="139" class="control-text">TLS, tool call mon.</text>\n'
    '  <text x="600" y="155" class="maturity">Avancé</text>\n'
    '\n'
    '  <!-- Stage 7 -->\n'
    '  <rect x="655" y="50" width="100" height="40" fill="#ccc" class="layer"/>\n'
    '  <text x="705" y="67" class="stage-label">7. Impact</text>\n'
    '  <text x="705" y="78" class="maturity">J+6</text>\n'
    '\n'
    '  <rect x="655" y="100" width="100" height="65" fill="#c0c0c0" class="layer"/>\n'
    '  <text x="705" y="115" class="control-text">Sauvegardes</text>\n'
    '  <text x="705" y="127" class="control-text">immuables,</text>\n'
    '  <text x="705" y="139" class="control-text">3-2-1-1-0, PRI</text>\n'
    '  <text x="705" y="155" class="maturity">Intermédiaire</text>\n'
    '\n'
    '  <!-- BLOCK symbols between stages -->\n'
    '  <text x="128" y="93" class="block">✕</text>\n'
    '  <text x="233" y="93" class="block">✕</text>\n'
    '  <text x="338" y="93" class="block">✕</text>\n'
    '  <text x="443" y="93" class="block">✕</text>\n'
    '  <text x="548" y="93" class="block">✕</text>\n'
    '  <text x="653" y="93" class="block">✕</text>\n'
    '\n'
    '  <!-- Key insight box -->\n'
    '  <rect x="25" y="185" width="730" height="55" fill="none" stroke="#000" stroke-width="1" stroke-dasharray="4,2"/>\n'
    '  <text x="390" y="202" class="stage-label" style="font-size:9px;">Enseignement clé</text>\n'
    '  <text x="390" y="216" class="control-text" style="font-size:8px;">Les contrôles « Basique » et « Intermédiaire » (étapes 1 à 5) auraient interrompu la kill chain à plusieurs reprises</text>\n'
    '  <text x="390" y="228" class="control-text" style="font-size:8px;">sans nécessiter de capacités de sécurité IA avancées. Les contrôles « Avancé » (étape 6) ajoutent une couche</text>\n'
    '  <text x="390" y="240" class="control-text" style="font-size:8px;">spécifique aux risques agentiques, mais ne compensent pas l\'absence des fondamentaux.</text>\n'
    '\n'
    '  <!-- Legend -->\n'
    '  <rect x="25" y="260" width="15" height="12" fill="#f5f5f5" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="48" y="270" class="maturity" style="font-style:normal;">Basique</text>\n'
    '  <rect x="100" y="260" width="15" height="12" fill="#e0e0e0" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="133" y="270" class="maturity" style="font-style:normal;">Intermédiaire</text>\n'
    '  <rect x="200" y="260" width="15" height="12" fill="#d0d0d0" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="223" y="270" class="maturity" style="font-style:normal;">Avancé</text>\n'
    '  <text x="290" y="270" class="block">✕</text>\n'
    '  <text x="310" y="270" class="maturity" style="font-style:normal;">= point d\'interruption potentiel</text>\n'
    '\n'
    '  <!-- Caption -->\n'
    '  <line x1="20" y1="290" x2="760" y2="290" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="20" y="308" class="caption"><tspan font-weight="bold">Figure 20.</tspan> Défense en profondeur appliquée à l\'Opération OpenClaw. Chaque étape de la Kill Chain est un point</text>\n'
    '  <text x="20" y="323" class="caption">d\'interruption potentiel (✕). L\'intensité croissante du fond reflète la progression du privilège attaquant. Le niveau de</text>\n'
    '  <text x="20" y="338" class="caption">maturité requis (Basique / Intermédiaire / Avancé) est indiqué sous chaque contrôle. L\'échec d\'un contrôle à une</text>\n'
    '  <text x="20" y="353" class="caption">étape doit être compensé par un contrôle à l\'étape suivante — aucun contrôle unique n\'est suffisant.</text>\n'
    '</svg>\n'
)

# ────────────────────────────────────────────────────────────
# SVG ANGLAIS (modifiable)
# ────────────────────────────────────────────────────────────
SVG_EN = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<svg xmlns="http://www.w3.org/2000/svg" width="780" height="480" viewBox="0 0 780 480">\n'
    '  <style>\n'
    '    text { font-family: "Times New Roman", Times, serif; }\n'
    '    .title { font-size: 11px; font-weight: bold; text-anchor: middle; }\n'
    '    .layer { stroke: #000; stroke-width: 1; }\n'
    '    .stage-label { font-size: 8px; font-weight: bold; text-anchor: middle; }\n'
    '    .control-text { font-size: 7.5px; text-anchor: middle; fill: #333; }\n'
    '    .maturity { font-size: 7px; text-anchor: middle; fill: #555; font-style: italic; }\n'
    '    .caption { font-size: 10px; text-anchor: start; }\n'
    '    .arrow { fill: none; stroke: #000; stroke-width: 0.6; marker-end: url(#arr); }\n'
    '    .block { font-size: 7px; text-anchor: middle; fill: #c00; font-weight: bold; }\n'
    '  </style>\n'
    '  <defs><marker id="arr" markerWidth="6" markerHeight="4" refX="6" refY="2" orient="auto"><polygon points="0 0, 6 2, 0 4" fill="#000"/></marker></defs>\n'
    '\n'
    '  <text x="390" y="20" class="title">DEFENSE IN DEPTH — KILL CHAIN DISRUPTION POINTS</text>\n'
    '  <line x1="20" y1="28" x2="760" y2="28" stroke="#000" stroke-width="0.6"/>\n'
    '\n'
    '  <line x1="40" y1="42" x2="740" y2="42" class="arrow"/>\n'
    '  <text x="390" y="38" class="maturity">Attack progression →</text>\n'
    '\n'
    '  <rect x="25" y="50" width="100" height="40" fill="#f5f5f5" class="layer"/>\n'
    '  <text x="75" y="67" class="stage-label">1. Recon.</text>\n'
    '  <text x="75" y="78" class="maturity">D−30 to D−15</text>\n'
    '  <rect x="25" y="100" width="100" height="65" fill="#eee" class="layer"/>\n'
    '  <text x="75" y="115" class="control-text">Public footprint</text>\n'
    '  <text x="75" y="127" class="control-text">reduction, banner</text>\n'
    '  <text x="75" y="139" class="control-text">hardening, awareness</text>\n'
    '  <text x="75" y="155" class="maturity">Basic</text>\n'
    '\n'
    '  <rect x="130" y="50" width="100" height="40" fill="#f5f5f5" class="layer"/>\n'
    '  <text x="180" y="67" class="stage-label">2. Weaponiz.</text>\n'
    '  <text x="180" y="78" class="maturity">D−15 to D−7</text>\n'
    '  <rect x="130" y="100" width="100" height="65" fill="#eee" class="layer"/>\n'
    '  <text x="180" y="115" class="control-text">Skill code review,</text>\n'
    '  <text x="180" y="127" class="control-text">publisher signing,</text>\n'
    '  <text x="180" y="139" class="control-text">extension allowlist</text>\n'
    '  <text x="180" y="155" class="maturity">Intermediate</text>\n'
    '\n'
    '  <rect x="235" y="50" width="100" height="40" fill="#f0f0f0" class="layer"/>\n'
    '  <text x="285" y="67" class="stage-label">3. Delivery</text>\n'
    '  <text x="285" y="78" class="maturity">D−7 to D</text>\n'
    '  <rect x="235" y="100" width="100" height="65" fill="#e8e8e8" class="layer"/>\n'
    '  <text x="285" y="115" class="control-text">KEV/CISA patching,</text>\n'
    '  <text x="285" y="127" class="control-text">phishing-resistant</text>\n'
    '  <text x="285" y="139" class="control-text">MFA, sandboxing</text>\n'
    '  <text x="285" y="155" class="maturity">Basic</text>\n'
    '\n'
    '  <rect x="340" y="50" width="100" height="40" fill="#e8e8e8" class="layer"/>\n'
    '  <text x="390" y="67" class="stage-label">4. Exploitation</text>\n'
    '  <text x="390" y="78" class="maturity">Day D</text>\n'
    '  <rect x="340" y="100" width="100" height="65" fill="#e0e0e0" class="layer"/>\n'
    '  <text x="390" y="115" class="control-text">Tool allowlist,</text>\n'
    '  <text x="390" y="127" class="control-text">agent permission</text>\n'
    '  <text x="390" y="139" class="control-text">restrictions</text>\n'
    '  <text x="390" y="155" class="maturity">Intermediate</text>\n'
    '\n'
    '  <rect x="445" y="50" width="100" height="40" fill="#e0e0e0" class="layer"/>\n'
    '  <text x="495" y="67" class="stage-label">5. Installation</text>\n'
    '  <text x="495" y="78" class="maturity">D to D+1</text>\n'
    '  <rect x="445" y="100" width="100" height="65" fill="#d8d8d8" class="layer"/>\n'
    '  <text x="495" y="115" class="control-text">Memory governance,</text>\n'
    '  <text x="495" y="127" class="control-text">token rotation,</text>\n'
    '  <text x="495" y="139" class="control-text">config integrity</text>\n'
    '  <text x="495" y="155" class="maturity">Intermediate</text>\n'
    '\n'
    '  <rect x="550" y="50" width="100" height="40" fill="#d8d8d8" class="layer"/>\n'
    '  <text x="600" y="67" class="stage-label">6. C2</text>\n'
    '  <text x="600" y="78" class="maturity">D+1 to D+5</text>\n'
    '  <rect x="550" y="100" width="100" height="65" fill="#d0d0d0" class="layer"/>\n'
    '  <text x="600" y="115" class="control-text">Egress allowlist,</text>\n'
    '  <text x="600" y="127" class="control-text">DLP, TLS inspect.,</text>\n'
    '  <text x="600" y="139" class="control-text">tool call monitoring</text>\n'
    '  <text x="600" y="155" class="maturity">Advanced</text>\n'
    '\n'
    '  <rect x="655" y="50" width="100" height="40" fill="#ccc" class="layer"/>\n'
    '  <text x="705" y="67" class="stage-label">7. Impact</text>\n'
    '  <text x="705" y="78" class="maturity">D+6</text>\n'
    '  <rect x="655" y="100" width="100" height="65" fill="#c0c0c0" class="layer"/>\n'
    '  <text x="705" y="115" class="control-text">Immutable backups,</text>\n'
    '  <text x="705" y="127" class="control-text">3-2-1-1-0 rule,</text>\n'
    '  <text x="705" y="139" class="control-text">incident response</text>\n'
    '  <text x="705" y="155" class="maturity">Intermediate</text>\n'
    '\n'
    '  <text x="128" y="93" class="block">✕</text>\n'
    '  <text x="233" y="93" class="block">✕</text>\n'
    '  <text x="338" y="93" class="block">✕</text>\n'
    '  <text x="443" y="93" class="block">✕</text>\n'
    '  <text x="548" y="93" class="block">✕</text>\n'
    '  <text x="653" y="93" class="block">✕</text>\n'
    '\n'
    '  <rect x="25" y="185" width="730" height="55" fill="none" stroke="#000" stroke-width="1" stroke-dasharray="4,2"/>\n'
    '  <text x="390" y="202" class="stage-label" style="font-size:9px;">Key takeaway</text>\n'
    '  <text x="390" y="216" class="control-text" style="font-size:8px;">"Basic" and "Intermediate" controls (stages 1–5) would have disrupted the kill chain at multiple points</text>\n'
    '  <text x="390" y="228" class="control-text" style="font-size:8px;">without requiring advanced AI security capabilities. "Advanced" controls (stage 6) add an AI-specific defense</text>\n'
    '  <text x="390" y="240" class="control-text" style="font-size:8px;">layer for agentic risks, but do not compensate for missing fundamentals.</text>\n'
    '\n'
    '  <rect x="25" y="260" width="15" height="12" fill="#f5f5f5" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="48" y="270" class="maturity" style="font-style:normal;">Basic</text>\n'
    '  <rect x="100" y="260" width="15" height="12" fill="#e0e0e0" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="133" y="270" class="maturity" style="font-style:normal;">Intermediate</text>\n'
    '  <rect x="200" y="260" width="15" height="12" fill="#d0d0d0" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="223" y="270" class="maturity" style="font-style:normal;">Advanced</text>\n'
    '  <text x="290" y="270" class="block">✕</text>\n'
    '  <text x="310" y="270" class="maturity" style="font-style:normal;">= potential disruption point</text>\n'
    '\n'
    '  <line x1="20" y1="290" x2="760" y2="290" stroke="#000" stroke-width="0.5"/>\n'
    '  <text x="20" y="308" class="caption"><tspan font-weight="bold">Figure 20.</tspan> Defense in depth applied to Operation OpenClaw. Each Kill Chain stage is a potential disruption point (✕).</text>\n'
    '  <text x="20" y="323" class="caption">Increasing background intensity reflects the attacker\'s escalating privilege. The maturity level required (Basic /</text>\n'
    '  <text x="20" y="338" class="caption">Intermediate / Advanced) is shown below each control. Failure of a control at one stage must be compensated by a</text>\n'
    '  <text x="20" y="353" class="caption">control at the next — no single control is sufficient.</text>\n'
    '</svg>\n'
)


def generate(lang=None):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    targets = []
    if lang != "en":
        targets.append(("FR", SVG_FR))
    if lang != "fr":
        targets.append(("EN", SVG_EN))
    for suffix, svg in targets:
        name = f"Figure20_Defense_{suffix}.png"
        path = os.path.join(OUTPUT_DIR, name)
        cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=path, dpi=DPI, output_width=WIDTH)
        print(f"  \u2713 {name} ({os.path.getsize(path)//1024} KB)")


if __name__ == "__main__":
    lang = sys.argv[1].lower() if len(sys.argv) > 1 else None
    generate(lang)
